#Executable could be a jar file, bash script or an out file generated by a c or c++ compiler
if [[ $1 == *.jar ]]
then
  timeout 120s java -jar $1 $2 $3
else
  timeout 120s $1 $2 $3
fi

if [ -e $3 ]
then
  java -jar tsp.jar $2 $3
fi
